### ISSUE TITLE
"zsh: command not found: solidity-docgen"

### ISSUE THREAD

**Issue by tnguyen42** [OpenZeppelin/solidity-docgen#105]
Hi,

All I did was `npm install solidity-docgen` followed by `solidity-docgen`, and I got the following error:
```
zsh: command not found: solidity-docgen
```

I've searched the issues and StackOverflow, but haven't been able to find the reason... I also resetted my terminal, just in case. It didn't help...
Does anyone have an idea of the reason, or has been able to reproduce the issue?

Thanks!

**Comment by tnguyen42** [comment]
For some reason, `solidity-docgen` failed to work but `npx solidity-docgen` made it.
Just in case this is truly an issue, I won't close it, but feel free to do so!

**Comment by frangio** [comment]
Hi @tnguyen42! This is standard behavior of npm for local installs. The executable is installed in `node_modules/.bin` and you should use `npx` to run the command.
