### ISSUE TITLE
Any way to exclude contracts from generation, not just docusaurus?

### ISSUE THREAD

**Issue by aleybovich** [OpenZeppelin/solidity-docgen#11]
If I specify `--exclude` then those contracts don't show in docusaurus, but are still generated. Is there a reason why they can't be also excluded from generation?

**Comment by ealmansi** [comment]
No technical reason why they cannot be excluded from generation. The generateDocs functions would need to be updated.

**Comment by frangio** [comment]
v0.2 (still in alpha) has an option to ignore files and directories.

https://github.com/OpenZeppelin/solidity-docgen/blob/8108281826cad7a7e9f75314620b3581581266e8/src/cli.js#L20-L21
