### ISSUE TITLE
Defining arbitrary attributes on items

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/solidity-docgen#131]
I would like to be able to define arbitrary attributes as part of a natspec comment that would be parsed and made available to the handlebars templates.

Potential syntax:

```solidity
/**
 * @notice Description...
 * !since v2.5.0
 */
contract Foo { ... }
```

See https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2054 for the original usecase.

**Comment by axic** [comment]
Heads up, this has been solved with `@custom:...` in 0.8.2.

**Comment by axic** [comment]
Is this supported now or is it still outstanding?

**Comment by frangio** [comment]
Yes, custom tags like `@custom:foo` are supported as of `0.5.13` by using `{{natspec.custom.foo}}` in the Handlebars template.

Thanks for following up on this!
