### ISSUE TITLE
Solidity was unable to compile because of the compiler version

### ISSUE THREAD

**Issue by shunp** [OpenZeppelin/solidity-docgen#166]
When trying to generate docs, I've encountered this problem.

### [Error Message]
ParserError: Source file requires different compiler version (current compiler is 0.6.4+commit.1dca32f3.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.5.16;
^---------------------^

### [My structure]

```
/root-project
    |--package.json
    |--/sub-project
          |--/contracts
          |--truffle-config.js
```

```sh
> solidity-docgen -i ./sub-project/contracts -o ./sub-project/docs
```

**Comment by abcoathup** [comment]
Hi @shunp!  

I’m sorry that you had this issue.  

Thanks so much for reporting it! The project owner will review and triage this issue during the next week.  In the meantime, you can try the following workaround:
Install the previous version which supported Solidity 0.5 (see https://github.com/OpenZeppelin/solidity-docgen/issues/133#issuecomment-581554574)
```
npm i solidity-docgen@0.3.14
```

**Comment by frangio** [comment]
Hi @shunp. Please take a look at [the changelog entry for 0.4.0](https://github.com/OpenZeppelin/solidity-docgen/blob/master/CHANGELOG.md#040).

>If you would like to upgrade `solidity-docgen` but continue using the 0.5
compiler, you can install `solc@0.5` in your project and run `solidity-docgen
--solc-module ./node_modules/solc`.

Let me know if you're able to fix it following these instructions.

**Comment by shunp** [comment]
@frangio @abcoathup 
Thank you for your comment.
It works successfully when using `solc@0.5.16`.
