### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by 0x6431346e** [OpenZeppelin/solidity-docgen#22]
Would be great to get this working on windows:

```
E:\repos\aragon\hack\website\node_modules\solidity-docgen\lib\index.js:134
    throw new Error(['Command line operation failed with code ' + commandOutput.code + '.', 'Standard error output: ' + commandOutput.stderr].join('\n'));
    ^

Error: Command line operation failed with code 1.
Standard error output: unrecognised option '-type'
```

The problematic line is: https://github.com/OpenZeppelin/solidity-docgen/blob/fc57890ff58ac434ddc6d5f54ab879c3b593772a/src/index.js#L113

**Comment by frangio** [comment]
Hey there. We've stopped maintaining v0.1 of `solidity-docgen`. Please check out #23 to learn about v0.2. It was a rewrite and `find` is not used anymore. If anyone finds issues on Windows please open a new issue.
