### ISSUE TITLE
Generating docs from a single .sol with 1+ contracts/interface will only output the last one

### ISSUE THREAD

**Issue by mr-ubik** [OpenZeppelin/solidity-docgen#227]
Generating docs from a single .sol with 1+ contracts/interface will only output the last one

Example:

File: `test.sol`

```solidity

interface A

interface B

```

Only docs for B will be generated in the file `test.md`

**Comment by frangio** [comment]
@mr-ubik Can you let me know what version you're running, and what command line flags you're using? Thanks.

**Comment by mr-ubik** [comment]
Version: `0.5.4`
Command: `solidity-docgen -i ../contracts -o md-build -t solidity-docgen-templates`

**Comment by frangio** [comment]
I can confirm this is a bug here:

https://github.com/OpenZeppelin/solidity-docgen/blob/3feedac5878a751fd5ec2d70d74d34f8931c40e1/src/page.ts#L96-L99

I'll try to fix it as soon as possible. Thank you for reporting!

**Comment by frangio** [comment]
@mr-ubik I've released `0.5.5` with a fix for this issue.
