### ISSUE TITLE
Support projects with dependencies

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/solidity-docgen#24]
v0.3 doesn't work when a project has dependencies (e.g. if they use OpenZeppelin contracts). We could use [resolver-engine](https://github.com/Crypto-Punkers/resolver-engine) to tackle this.

**Comment by tsudmi** [comment]
Are there any updates on that?

**Comment by frangio** [comment]
Contributions are welcome to add resolver-engine to the compilation code!

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/solidity-docgen/commit/e316e723b342275b62765bdbecda8969ecc3fc33.
