### ISSUE TITLE
Cannot destructure property 'content' of 'this.input.sources[source]' as it is undefined.

### ISSUE THREAD

**Issue by chapati23** [OpenZeppelin/solidity-docgen#255]
hey, gave this package a try today and ran into this error:

`TypeError: Cannot destructure property 'content' of 'this.input.sources[source]' as it is undefined.`

this is the failing line: https://github.com/OpenZeppelin/solidity-docgen/blob/master/src/solc.ts#L210

the `source` argument is `@openzeppelin/contracts/access/AccessControl.sol` so I'm guessing this has something to do with solidity-docgen not looking inside `node_modules` for imported packages?

or maybe I'm misunderstanding something here 🤔

**Comment by frangio** [comment]
Thank you for reporting! Imported packages should be supported, but this piece of code is new and I had not tested it with dependencies.

I'll publish a fix but in the meantime you can use version 0.5.7.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/solidity-docgen/commit/2d1e2fea8a5504b5075a172635664d02aae642ab. Released in 0.5.9!

**Comment by chapati23** [comment]
works! thanks for fixing this so quickly 🙌
