### ISSUE TITLE
Does not parse private functions

### ISSUE THREAD

**Issue by Yorkemartin** [OpenZeppelin/solidity-docgen#265]
solidity-docgen seems to not parse internal functions, though I'm getting one or two through. Is this intentional?

**Comment by Yorkemartin** [comment]
I see in source.ts - `get ownFunctions()` there is  .filter(n => n.visibility !== 'private').
I commented it out but private functions still are not generated.

**Comment by frangio** [comment]
Internal functions should be included in the output. Private functions aren't. solidity-docgen aims to produce documentation for users of the external or internal APIs of a contract, and private functions are seen as implementation detail.

Can you describe a bit more why you want to include private functions in the output? Who is the target reader of the documentation you're producing?

**Comment by Yorkemartin** [comment]
The goal of the documented private functions is to help developers understand the internal processes of a larger function. In this instance many private functions are called in sequence to process a type of calculation. Documenting each private function will make the mechanics easier for a reader to grasp. It will also help with auditors looking to quickly gain a high level overview of the process of a contract. The goal initially was to document each external function in the contract interface, inherit those in the main contract, and provide further documentation of the internal processes involved in the externally available functions.

**Comment by frangio** [comment]
I see. I'll take a look at adding an option to include private functions tomorrow.

**Comment by frangio** [comment]
@Yorkemartin I added a new array variable in the contract template: `privateFunctions`. It can be used like `ownFunctions` or `functions` to produce documentation for all own private functions. (Note: they are not inherited.)

Released now in the latest version!
