### ISSUE TITLE
Support the version number and kind (doctype)

### ISSUE THREAD

**Issue by axic** [OpenZeppelin/solidity-docgen#283]
Since 0.6.11 (with https://github.com/ethereum/solidity/issues/8922) the compiler outputs a `version` tag (set to `1`) and a `kind` tag (set to `user` or `dev`).

It would be useful to support these for forward-compatibility, though I am not sure if there's an immediate change to be made. Ideally I would say the tool should turn into some legacy mode if `version` tag is missing.

However we do plan to make changes to the format and introduce `version: 2` not too far into the future.

**Comment by frangio** [comment]
Thanks for the issue! I think as you have seen this project doesn't use the NatSpec output, and if I understand correctly `version` and `kind` are found there. So I think I can close this as there is nothing we need to do.

**Comment by axic** [comment]
It doesn't? I may be mistaken then, but I did see a lot things called natspec in templates and `source.ts`.

Okay I see now in https://github.com/OpenZeppelin/solidity-docgen/blob/4374a6d15c3688c485c640f8cc6ae1a212e3aedb/src/source.ts#L430, you are trying to rebuild natspec out of the AST.

I hope this does not mean that we have less flexibility upgrading mechanisms 😬

**Comment by frangio** [comment]
We're already adapting ASTs from previous Solidity versions so we can treat them all uniformly, so if anything changes in the future we will do the same!
