### ISSUE TITLE
Removing dependency on the AST

### ISSUE THREAD

**Issue by axic** [OpenZeppelin/solidity-docgen#284]
Apologies if this question makes little sense as I have not reviewed the entire codebase. However I am wondering if the dependency on the AST could be removed and depending on the "public" Natspec and ABI outputs would be enough to accomplish everything. And if not, what are the missing details in these two?

**Comment by frangio** [comment]
If I remember correctly, the compiler's NatSpec outputs only include external (or public) functions. It's important for this project to be able to document internal functions.

I believe there were other things missing back when I initially built this. But overall working with the AST directly has provided a lot of flexibility. I'm happy to help figure out how to improve the compiler's NatSpec outputs but I'd like to keep this flexibility for now.
