### ISSUE TITLE
Allow to register additional handlebars helpers

### ISSUE THREAD

**Issue by Pzixel** [OpenZeppelin/solidity-docgen#299]
(or at least add more helpers)

The current problem is that existing helpers couldn't fit all the requirements. For example consider [following handlebars](https://github.com/Uniswap/uniswap-docs/blob/main/contract.hbs). Look at this place:

```md
#### Parameters:
| Name | Type | Description                                                          |
| :--- | :--- | :------------------------------------------------------------------- |
{{#natspec.params}}
|`{{param}}` | {{#lookup ../args.types @index}}{{/lookup}} | {{ description }}{{/natspec.params}}{{/if}}
{{#if natspec.returns}}
```
It looks just fine but natspec allows `description` to have newlines (and this is what happens when you have a really long comment). If this happens markup get ruined because it's get rendered into something like:
```md
#### Parameters:
| Name | Type | Description                                                          |
| :--- | :--- | :------------------------------------------------------------------- |
|`paramName` | address[] | SomeDescription is reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeealy long
and goes here 
|`paramName2` | address | Another desc here
```

which renders as

![image](https://user-images.githubusercontent.com/11201122/121506249-398def00-c9ec-11eb-92cc-bfc0ffafb6dc.png)

In this specific case we would probably like to write:

```md
#### Parameters:
| Name | Type | Description                                                          |
| :--- | :--- | :------------------------------------------------------------------- |
{{#natspec.params}}
|`{{param}}` | {{#lookup ../args.types @index}}{{/lookup}} | {{#removeNewlines description }}{{/natspec.params}}{{/if}}
{{#if natspec.returns}}
```
But it's not something we can express in handlebars. We need to either has some specific helper (like string.replace(pattern, newValue) or allow to register an arbitrary file like we do register contract and allow user to use these helpers. For example we could just search for `handlerbarsHelpers.js` of some known form and then include all its functions as handlebars helpers.

I could try to make a PR if you feel like this is something you can merge.

**Comment by Pzixel** [comment]
Another example would be `any/all` (for example "render header only if any of items has some condition evaluated to true)

**Comment by frangio** [comment]
Hey sorry that this is not documented but you can already register additional helpers as shown here: https://github.com/OpenZeppelin/solidity-docgen/issues/213#issuecomment-651365558
