### ISSUE TITLE
Support solc 0.4.x in solidity-docgen 0.2.0-alpha.1

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/solidity-docgen#30]
solidity-docgen 0.2.0-alpha.1 supports only contracts compiled under solc v0.5.x (i.e., starting with `pragma solidity ^0.5.0` or similar).

In order to extend this version of `solidity-docgen` to support earlier versions of `solc`, I believe that in file `compile.js` line 48:
```
  const solcOutputString = _solc.default.compile(JSON.stringify(inputJSON));
```
You should determine which version of `solc` is used in the target project, and for an earlier version, replace `compile` with `compileStandard`.

I suppose that this is rather difficult, since theoretically, one may use different `solc` versions for different source files in the given project. Perhaps `compileStandard` works in both cases, in which case you may simply go ahead and use it inside of `compile`.

For anyone here eager to use solidity-docgen 0.2.0-alpha.1 on a project based on solc version earlier than 0.5.x, here is a "hot-fix" which I have established (executed automatically at the end of `npm install`). Please note that this patch relies on `truffle` being part of your project, in order to force its `solc` version on `solidity-docgen`.

In file `package.json`, add something like:
```
  "scripts": {
    "install": "node fix-modules.js",
    "docify": "node_modules/.bin/solidity-docgen -c the_relative_path_to_your_contracts"
  }
  "dependencies": {
    "truffle": "4.1.14",
    "solidity-docgen": "0.2.0-alpha.1"
  }
```
Next to file `package.json`, add file `fix-modules.js`:
```
const fs = require("fs");

try {
    fs.closeSync(fs.openSync("./node_modules/run-once", "wx"));
}
catch (error) {
    console.error("This script should not run more than once");
    process.exit();
}

function fix(fileName, tokens) {
    console.log("Fixing " + fileName);
    try {
        let data = fs.readFileSync(fileName, {encoding: "utf8"});
        for (const token of tokens)
            data = data.split(token.prev).join(token.next);
        fs.writeFileSync(fileName, data, {encoding: "utf8"});    
    } catch (err) {
        console.log("Error fixing " + fileName);
    }
}

function copyDir(src, dest) {
    fs.mkdirSync(dest);
    for (const file of fs.readdirSync(src)) {
        if (fs.lstatSync(src + "/" + file).isDirectory()) {
            copyDir(src + "/" + file, dest + "/" + file);
        }
        else {
            fs.copyFileSync(src + "/" + file, dest + "/" + file);
        }
    }
};

fix("./node_modules/solidity-docgen/dist/gather/solidity/compile.js", [
    {prev: "_solc.default.compile", next: "_solc.default.compileStandard"}]
);

copyDir("./node_modules/truffle/node_modules/solc", "./node_modules/solidity-docgen/node_modules/solc");
```
Now, after `npm install`, you can generate documentation to your projects via `npm run docify`.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/solidity-docgen/commit/83880bb9d9bf8ecb86a9948290b509aa32b9c1f8.

It only works with solc >= 0.4.24, though.
