### ISSUE TITLE
Output file 'index.md' is in conflict with 'gitbook'

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/solidity-docgen#31]
Trying to take the output folder and pass it to [gitbook](https://www.npmjs.com/package/gitbook), file `index.md` generated by `solidity-docgen` yields a problem in the output of `gitbook`, which relies on a file with the same name as part of its output.

Subsequently, I can solve this by renaming your `index.md`, but you may want to consider naming it something different (like `main.md` or similar).

Following [my previous issue](https://github.com/OpenZeppelin/solidity-docgen/issues/30), one can "hot-fix" this by adding the following lines in file `fix-modules.js`:
```
fix("./node_modules/solidity-docgen/dist/gather/index.js", [
    {prev: "return 'index';", next: "return 'main';"}]
);
```
Thanks

**Comment by frangio** [comment]
Thanks for reporting @barakman!

>relies on a file with the same name as part of its output.

Can you confirm that you meant "output" here, and not input? In that case, have you considered setting the output directory of solidity-docgen to a different directory?

**Comment by barakman** [comment]
@frangio:

Sorry, I indeed meant "input".

When I run gitbook, it creates everything under a folder named `_book`.

Inside this folder, it creates a folder named `docs` (unrelated to the fact that you also create such folder by default, and these two folders are located in different places anyway).

Then it takes all the files which are specified in `SUMMARY.md`, copies them into `_book/docs`, and for each `md` file creates a corresponding `js` file in that same folder.

Finally, inside `_book`, it also creates a file named `index.js`, which does not collide with the file which corresponds to your `index.md` (since this one is located under `_books/docs`).

The collision which I was referring to stems from an internal behavior of gitbook (so one may claim that I should have posted this problem on their GitHub, but you're currently on alpha-phase so I think it might be better that you align with them rather than vice-versa).

As I said, for each `md` file specified in `SUMMARY.md`, gitbook generates a corresponding `js` file under `_book/docs`, and then generates a `index.js` file under `_books`.
In this `index.js` file, it writes an `href` entry for each `js` file corresponding to your `md` file, which looks more or less like this:
```
        <li class="chapter " data-level="1.2" data-path="docs/main.html">
                <a href="docs/main.html">
                    main
                </a>
        </li>
```
When the name of this file is `index.js`, gitbook for some reason omits it and writes `<a href="docs/">` instead.

So your `index.md` triggers a "chain action" which eventually yields a bad link in gitbook's output.

**Comment by frangio** [comment]
Thanks for such a detailed explanation!

So if I understand correctly the problem is that the link in gitbook's table of contents does not work because gitbook omits the file name in the href.

>When the name of this file is index.html, gitbook for some reason omits it and writes \<a href="docs/"\> instead.

This is actually pretty standard behavior, and it's why I named the file `index.md` in the first place.

Have you confirmed that the link doesn't work when the site is published? I can see how the link would not work if you're viewing the file locally through the file system, but it should work through an http server that knows to serve `index.html` by default (e.g. `python -m http.server`).

**Comment by barakman** [comment]
@frangio:

You're right. I've only checked this when viewed on my local machine (i.e., via the file system).

It did not occur to me that it might work differently when served, so I feel kinda stupid for bringing this up.

I'll give it a go on a Python server running on localhost, but I'm pretty confident that you're right, and that this file should not be renamed.

Thank you very much for your help on this one :)

I think that this issue may be closed at this point... Thanks!
