### ISSUE TITLE
Support for 0.8.0

### ISSUE THREAD

**Issue by JackBekket** [OpenZeppelin/solidity-docgen#322]
https://github.com/OpenZeppelin/openzeppelin-contracts seems like 0.8.0 become standard, can we make docgen now support generation for 0.8.0 ?

**Comment by frangio** [comment]
Hi @JackBekket. You should be able to use 0.8 using the [steps shown in the readme for 0.7](https://github.com/OpenZeppelin/solidity-docgen#solidity-07). Have you tried this?

**Comment by YanLong-111** [comment]
It seems that it cannot be applied to the version above 0.8.0. When I compile my project, it reminds me: Error: Solidity was unable to compile. contracts/Ownable.sol:3:1: ParserError: Source file requires different compiler version (current compiler is
     0.7.6+commit.7338295f.Emscripten.clang)-note that nightly builds are considered to be strictly less than the released version
     pragma solidity ^0.8.0;
     ^---------------------^
* I am using the 0.8.0 version of the standard Ownable*

**Comment by JackBekket** [comment]
@YanLong-111 

I suggest you to check your solc compiler version

Note, that global solc version can be different from solc, that you use locally in your repo 

I have been required to install some additional package (don't remember its name), which has allowed me to have several versions of solc and switching between them, in order to make solidity-docgen work

**Comment by JackBekket** [comment]
However, generated docs was look.. let's say it was not in good shape, so I decided to refuse using solidity-docgen after all

**Comment by YanLong-111** [comment]
@JackBekket 
Oh, thank you, I generated the document in an inexplicable situation (it returned me an error message, but still generated the document), but this is not what I want, so I support your point of view, and also thank the developers Work hard, hope it will get better

**Comment by frangio** [comment]
Closing this as support for 0.8 is there.

If you were unhappy with the output please share! This tool requires a lot of customization currently. Feedback is welcome.
