### ISSUE TITLE
Changing solc-module error

### ISSUE THREAD

**Issue by VakhtanhChikhladze** [OpenZeppelin/solidity-docgen#328]
$ npx solidity-docgen --solc-module node_modules/solc
    TypeError: this.solc.compileStandardWrapper is not a function

**Comment by frangio** [comment]
The argument to `--solc-module` should be `solc` or `./node_modules/solc`.

**Comment by VakhtanhChikhladze** [comment]
% npx solidity-docgen -i contracts -o docs --solc-module ./node_modules/solc
    TypeError: this.solc.compileStandardWrapper is not a function
And if i type this:
% npx ./node_modules/solc --version 
0.8.0+commit.c7dfd78e.Emscripten.clang

**Comment by frangio** [comment]
Have you tried with `--solc-module solc`?

What is the version of `solidity-docgen`?

If nothing works please run `env DEBUG='*' npx solidity-docgen ...` to retrieve the stack trace.

**Comment by VakhtanhChikhladze** [comment]
yes, i tried `--solc-module solc` and i got the same error

% npx solidity-docgen --version
solidity-docgen/0.3.14 darwin-x64 node-v16.10.0

% env DEBUG='*' npx solidity-docgen
  @oclif/config reading core plugin /Users/ippolit/project/node_modules/solidity-docgen +0ms
  @oclif/config loadJSON /Users/ippolit/project/node_modules/solidity-docgen/package.json +0ms
  @oclif/config loadJSON /Users/ippolit/project/node_modules/solidity-docgen/oclif.manifest.json +4ms
  @oclif/config loadJSON /Users/ippolit/project/node_modules/solidity-docgen/.oclif.manifest.json +1ms
  @oclif/config reading user plugins pjson /Users/ippolit/.local/share/solidity-docgen/package.json +0ms
  @oclif/config loadJSON /Users/ippolit/.local/share/solidity-docgen/package.json +2ms
  @oclif/config config done +1ms
  solidity-docgen init version: @oclif/command@1.8.0 argv: [] +0ms
Error: Solidity was unable to compile. contracts/MyContract.sol:2:1: ParserError: Source file requires different compiler version (current compiler is 0.5.17+commit.d19bba13.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity >=0.8.0;
^----------------------^
 (And 34 other errors...)
    at Object.<anonymous> (/Users/ippolit/project/node_modules/solidity-docgen/dist/compile.js:53:19)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/ippolit/project/node_modules/solidity-docgen/dist/compile.js:5:58)

**Comment by VakhtanhChikhladze** [comment]
Ok, fine, i now i get another error.
I have a tree of my project like this:
.
├── contracts
│   ├── MyContract.sol
├── openzeppelin
│   ├── contracts
│   │   ├── README.md
│   │   ├── proxy
│   │   │   ├── transparent
│   │   │   │   ├── ProxyAdmin.sol
│   │   │   │   └── TransparentUpgradeableProxy.sol

And if i type 
% npx solidity-docgen --solc-module solc 
    Error: Solidity was unable to compile. ParserError: Source 
    "openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol" not found: Cannot 
    find module 'openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol'
    Require stack:
    - /Users/ippolit/proj/node_modules/solidity-docgen
    /dist/solc.js
    - /Users/ippolit/proj/node_modules/solidity-docgen
    /dist/docgen.js
    - /Users/ippolit/proj/node_modules/solidity-docgen
    /dist/cli.js
     --> contracts/MyContract.sol:4:1:
      |
    4 | import "../openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol";
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

     (And 24 other errors...)
     
How to not include openzeppelin contracts?
