### ISSUE TITLE
trouble in solidity-docgen

### ISSUE THREAD

**Issue by VakhtanhChikhladze** [OpenZeppelin/solidity-docgen#329]
% npx solidity-docgen -i contracts -o docs --solc-module ./node_modules/solc
TypeError: this.solc.compileStandardWrapper is not a function
And if i type this:
% npx ./node_modules/solc --version
0.8.0+commit.c7dfd78e.Emscripten.clang

**Comment by frangio** [comment]
Continuing the conversation in https://github.com/OpenZeppelin/solidity-docgen/issues/328.
