### ISSUE TITLE
Output of v0.2.0-alpha.1 is in ambiguous format

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/solidity-docgen#33]
v0.2.0-alpha.1 generates a bunch of `md` files (i.e., `md` extension in the name of each file).

However, the contents of each file seems to be in `html` format, while the original `md` data is now embedded into the `html` tags, for example:
```
<div class="contracts">
## Contracts
...
```
This seems to defeat the purpose of providing `md` output.

For example, I cannot use these file for my GitHub documentation.

Would it be possible to a `--format` argument which will determine the actual format of the output files?

Thanks

**UPDATE:**

Perhaps my description above isn't accurate.

The output files are displayed well in a markdown editor, with the exception of the titles themselves (anything preceded by one or more `#`).

Once I remove the `<div class=\"contracts\"> ... </div>` encapsulation in each file, this problem is resolved.

Following [my previous issue](https://github.com/OpenZeppelin/solidity-docgen/issues/30), one can "hot-fix" this by adding the following lines in file `fix-modules.js`:
```
fix("./node_modules/solidity-docgen/dist/render/index.js", [
    {prev: "'<div class=\"contracts\">', sections.map(renderSection), '</div>'", next: "sections.map(renderSection)"}]
);
```

**Comment by frangio** [comment]
The markdown files output by default now no longer have HTML in them. Moreover the output is now fully customizable.
