### ISSUE TITLE
documenting Struct/ Enum/ Constant  outside of contract

### ISSUE THREAD

**Issue by ghost** [OpenZeppelin/solidity-docgen#333]
Hi, I'm attempting to document an [EIP-2535](https://eips.ethereum.org/EIPS/eip-2535) Diamond contract that utilizies an 'AppStorage' pattern such as in [AAVEGotchi](https://github.com/aavegotchi/aavegotchi-contracts/blob/master/contracts/Aavegotchi/libraries/LibAppStorage.sol)  Thing is this pattern makes extensive use of structs outside of contracts.  To which I cant seem to docgen to register it.

Is documenting structs outside of contracts possible, or if not, planned to be implemented?

Thanks!

**Comment by Joe-mcgee** [comment]
specifically speaking
```
/**
* Some documentation about A
* @param b some documentation about
*/
struct A {
uint256 b;
}

contract {
...
}
}
```

**Comment by frangio** [comment]
Thanks for reaching out @Joe-mcgee. This is not currently supported. I'm interested in it but the code is structured around documenting contracts, and I haven't figure out how to implement it.

**Comment by Joe-mcgee** [comment]
Thanks for looking into it and letting me know @frangio :)

**Comment by frangio** [comment]
@miltonjonat This is currently supported in the 0.6 release.

**Comment by miltonjonat** [comment]
Ok @frangio thanks! Is there any open issue covering having NatSpec comments showing up in structs?
