### ISSUE TITLE
Support of array[] type in params and returns

### ISSUE THREAD

**Issue by nksazonov** [OpenZeppelin/solidity-docgen#336]
As discovered, solidity-docgen doesn't include array types (e.g. `int[]`) into generated doc from params or returns: square brackets simply don't pass the regex of [`genNatSpec()`](https://github.com/OpenZeppelin/solidity-docgen/blob/master/src/source.ts#L577):
`const paramMatches = content.match(/(\w+) ([^]*)/);`

Are there any intentions of supporting that soon?

**Comment by frangio** [comment]
Can you provide an example NatSpec text that fails to parse?

Are you interested in suggesting a fixed regex?

**Comment by nksazonov** [comment]
Unfortunately, I don't have enough time to fully explore solidity-docgen code, but as I can see from [here](https://github.com/OpenZeppelin/solidity-docgen/blob/master/src/source.ts#L564), the function iterates for each of the NatSpec tags and, if available (e.g. in _@​param_ and _@​return_), separates _param_ and _description_.
Thus, at first, _param_ and _description_ must be a single string, but in solc ^0.6.0 _param_ and _description_ are represented as a key-value pair of an (_param_, _returns_ etc.) object of a function (discovered in Remix IDE). Therefore I can deduce, that you concatenate these on your side. Am I right with all the consumptions above?

So, this was the NatSpec example I was playing with
```
{
	"methods": {
		"setGetNumbers(int256[])": {
			"details": "[]test []",
			"params": {
				"_numbers": "[] test int[] numbers"
			},
			"returns": {
				"numbers": "[] test int[] numbers"
			}
		}
	}
}
```

And the proposed regex is `/(\w+(\[\])*)([^]*)/`, which will support adding `[]` multiple times (hey multidimensional arrays!) at the end of the variable name.

**Comment by frangio** [comment]
Sorry this actually seems to work correctly. This is what I'm doing:

```
  /// @param xs list of integers
  function ary(int[] memory xs) external {}
```

In the contract.hbs template I have:

```
{{#each functions}}
{{#each natspec.params}}
{{param}}: {{description}}
{{/each}}
{{/each}}
```

And it correctly generates `xs: list of integers`.

**Comment by frangio** [comment]
Maybe the error is that you're writing something like `@param xs[] list of integers`?

But I don't think you should include the brackets there.
