### ISSUE TITLE
v0.2.0-alpha.1 parses only `dev` tags

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/solidity-docgen#34]
The only tag parsed by v0.2.0-alpha.1 is the `dev` tag, in file `extract.js` line 185:
```
  const matches = documentation.match(/^@dev[\t-\r \xA0\u1680\u2000-\u200A\u2028\u2029\u202F\u205F\u3000\uFEFF]+((?:(?!^@[0-9A-Z_a-z]+)[\0-\uFFFF])*)/m);
```
Are there any plans to extend this any time soon to support the other tags, such as `title`, `param`, `return` and `notice`?

Most important is the `param` tag. In v0.1.1, this tag is supported in file `document.js`, in functions `EventDetails`, `ModifierDetails` and `FunctionDetails`.

In case you are not planning to support the `param` tag in the near future, how might I easily incorporate this code into v0.2.0-alpha.1?

Thanks

**Comment by frangio** [comment]
Some discussion in the [community forum](https://forum.zeppelin.solutions/t/solidity-docgen-v0-2-0-alpha-1-parses-only-dev-tags/895).

Summing up: we're interested in supporting `@param` and `@return` as well.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/solidity-docgen/commit/3479ef4c6f8a024cc2450e39d27091f2a4a5ea13.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/solidity-docgen/commit/a07a46b9c2725500a7d93a603c23599adf77716f.
