### ISSUE TITLE
Possible to document structs and enums?

### ISSUE THREAD

**Issue by asselstine** [OpenZeppelin/solidity-docgen#346]
We'd like to have structs as part of the generated output.  Is this possible?

**Comment by frangio** [comment]
Should be possible. Take a look at this test template: https://github.com/OpenZeppelin/solidity-docgen/blob/master/fixtures/struct-enum/templates/contract.hbs

**Comment by frangio** [comment]
Closing as this is currently supported, shown in the link above.
