### ISSUE TITLE
inheritdoc

### ISSUE THREAD

**Issue by drortirosh** [OpenZeppelin/solidity-docgen#356]
inheritdoc is a great option, but currently need to be written on each item.
is it possible to globally enable inheritdoc ?

**Comment by frangio** [comment]
Yes. I want to implement this because it's the default Solidity behavior.

Are you using the rewrite that is currently in beta? This would probably be added there only.

**Comment by drortirosh** [comment]
we actually just started to use the master. 
how stable is the rewrite? should we use that ?

**Comment by frangio** [comment]
Implemented inheritdoc by default.
