### ISSUE TITLE
Version 0.6.0-beta.3 not distributed properly, is empty package

### ISSUE THREAD

**Issue by sambacha** [OpenZeppelin/solidity-docgen#361]
installing `solidity-docgen` with at least 0.6.0-beta.3 does not work

installing `solidity-docgen` version 0.5.16 works

**Comment by frangio** [comment]
0.6.0-beta.3 is not empty, but it was incorrectly tagged `latest` which has now been reset to 0.5.16.

Sorry about the inconvenience!

**Comment by sambacha** [comment]
Thank you for quick turnaround! Enjoy your weekend
