### ISSUE TITLE
Docgen task : provide sourcesDir

### ISSUE THREAD

**Issue by aelmanaa** [OpenZeppelin/solidity-docgen#378]
Hello and thank you very much for this plugin

A question regarding:

https://github.com/OpenZeppelin/solidity-docgen/blob/d7c993b2a9cee46eff4d24e61a76a822f864b691/src/hardhat/index.ts#L10

can't we provide our own 'sourcesDir' ?  THe default behaviour should be indeed `config.paths.sources` but we should also be able to override it if we want

**Comment by frangio** [comment]
Can you share the exact use case? I guess it could be possible to select a subdirectory of `config.paths.sources`, but it needs to be a subdirectory because we need Hardhat to compile these sources.

**Comment by aelmanaa** [comment]
HI @frangio 

we have 2 repos: 

- One containing the docs
- One containing the smart contracts 

I'd like to automatically generate the API reference from the docs repos. I guess I could also write a script to pull the repo, generate the API reference

**Comment by frangio** [comment]
Closing as needing further information.
