### ISSUE TITLE
No line breaks

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/solidity-docgen#38]
For non-bullet lines, the MD (MarkDown) standard dictates that in order to create a line break between two lines, they must be separated by an empty line.

In other words, and MD-rendering application merges every two consecutive lines which are not separated by at least one empty line.

Naturally, we don't add empty lines when we write documentation in our code (in Solidity, such paragraphs would typically be under the `@title` or `@dev` tags).

Is there any way for you to fix that in the package itself?

It cannot be resolved via the HBS (HandleBars) configuration file.

Thanks

**Comment by frangio** [comment]
>Naturally, we don't add empty lines when we write documentation in our code (in Solidity, such paragraphs would typically be under the @title or @dev tags).

Is there a reason why you wouldn't want to add empty lines? That's what we're doing in OpenZeppelin.

See [this comment](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/2187fae1546141b40a1222d6b06420218ed9ea47/contracts/token/ERC721/ERC721.sol#L269-L272) in for example, reproduced below.

```
     * @dev Internal function to invoke {IERC721Receiver-onERC721Received} on a target address.
     * The call is not executed if the target address is not a contract.
     *
     * This function is deprecated.
```

**Comment by barakman** [comment]
@frangio:
Yes, because in a well-documented contract, it would yield a lot of empty lines.
In addition to that, I don't think that one should document their code according to MD rules.
Thanks in any case :)

**Comment by frangio** [comment]
>Yes, because in a well-documented contract, it would yield a lot of empty lines.

Definitely, though I really don't see how this is a problem.

We want this tool to be agnostic to the format of the documentation strings. Could be Markdown, or AsciiDoc, or whatever. So I wouldn't want to do any specific processing of the text.
