### ISSUE TITLE
astNode undefined

### ISSUE THREAD

**Issue by swtrse** [OpenZeppelin/solidity-docgen#381]
Despite many examples here, in the current version astNode is always undefined.

For example: https://github.com/OpenZeppelin/solidity-docgen/issues/302

**Comment by frangio** [comment]
In the new version `astNode` is no longer needed, you can access all node properties directly. I.e. `{{astNode.parameters}}` becomes `{{parameters}}`.

What do you want to do?

**Comment by swtrse** [comment]
In this case
I want to expand the generated markdown for events to include the information if the parameter is indexed or not.

**Comment by frangio** [comment]
Ok I see. I've just published a new release that should allow you to write something like this for events:

```
{{#if natspec.params}}
| Name | Type | Indexed | Description |
| ---- | ---- | ------- | ----------- |
{{#each params}}
| {{name}} | {{type}} | {{indexed}} | {{{joinLines natspec}}} |
{{/each}}
{{/if}}
```

All other properties of [VariableDeclaration](https://solidity-ast.netlify.app/interfaces/variabledeclaration) are available inside `{{#each params}}` as well.

**Comment by swtrse** [comment]
Working like a charm. thx
