### ISSUE TITLE
How to format a text as code inside a comment?

### ISSUE THREAD

**Issue by swtrse** [OpenZeppelin/solidity-docgen#382]
Example:
```
Emits an [`OwnershipTransferred`](#ownershiptransferred) event indicating the renounced ownership.
```
got renderted into
```
Emits an [&#x60;OwnershipTransferred&#x60;](#ownershiptransferred) event indicating the renounced ownership.
```
which prevents the text to be displayed correctly. It should be rendert in this case to.
```
Emits an [`OwnershipTransferred`](#ownershiptransferred) event indicating the renounced ownership.
```

How can I achieve this?

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/solidity-docgen/commit/bef7a32802945c0a66eabea6d33e223d2f3f6463.

**Comment by swtrse** [comment]
Perfect.
It's working and even links to an anchor work fine.
