### ISSUE TITLE
Export docs into respective files

### ISSUE THREAD

**Issue by mehtaculous** [OpenZeppelin/solidity-docgen#384]
Is it possible to configure the generator to export the docs into separate files based on the contract names?

Currently it just exports everything into a single file called `index.md` when running `npx hardhat docgen`

**Comment by frangio** [comment]
Yes, you can can try `pages: 'items'` or `pages: 'files'` in the config. Result will differ depending on whether you have multiple items in each file.

So in hardhat.config.js/ts you should add:
```
docgen: {
  pages: 'items',
},

**Comment by mehtaculous** [comment]
`pages: 'files'` is exactly what I was looking for and worked like a charm. thanks for the help and quick response ser

on a side note, is there a place I can see all the options for hardhat config? couldn't seem to find it anywhere..

**Comment by frangio** [comment]
Yeah: [here](https://github.com/OpenZeppelin/solidity-docgen/blob/master/src/config.ts). Link is at the bottom of the readme as well.

**Comment by mehtaculous** [comment]
ahhh didn't realize that was for hardhat..thank you!

sorry but ran into a minor issue..seems that `docgen` is generating library contracts (ie OpenZeppelin) with the `.sol` extension instead of `.md`. is this normal behavior?

**Comment by frangio** [comment]
No, I think there was a bug. Just published a fix.
