### ISSUE TITLE
Adding documentation of Interface to Contract documentation

### ISSUE THREAD

**Issue by swtrse** [OpenZeppelin/solidity-docgen#385]
Hi, again :)

I have a case of a contract with an interface.

The interface defines an event.
The event in the interface is documented and shown in the created documentation.
Documentation is set to create an md file for every sol file.

The md-file for the contract does not list the events.
Since evens can not be overridden in the contracts i can not use inheritdoc.
Is there a way to use inheritdoc or any other way to inject the documentation of the event from the interface to the contract?

**Comment by frangio** [comment]
Yes, this kind of use case is where you should get into writing helpers. You can implement a helper that given a contract finds all of its parents and extracts all inherited events.

**Comment by frangio** [comment]
Here's a way which you could get what you want.

**hardhat.config.js**
```javascript
...
  docgen: {
    templates: 'docgen',
  },
...
```

**docgen/helpers.js**
```javascript
const { findAll } = require('solidity-ast/utils');

module.exports = {
  eq: (a, b) => a === b,

  /** @this {import('solidity-docgen').DocItemWithContext} */
  allEvents() {
    if (this.nodeType === 'ContractDefinition') {
      const { deref } = this.__item_context.build;
      const parents = this.linearizedBaseContracts.map(deref('ContractDefinition'));
      return parents.flatMap(p => [...findAll('EventDefinition', p)]);
    }
  },
};
```

**docgen/contract.hbs**
```handlebars
{{>common}}

{{#each (allEvents)}}
{{#hsection}}
{{>item}}
{{/hsection}}
{{/each}}

{{#each items}}
{{#unless (eq nodeType "EventDefinition")}}
{{#hsection}}
{{>item}}
{{/hsection}}
{{/unless}}

{{/each}}
```


I realize it should be a little easier but I'm learning from this, still figuring out how to best enable this kind of customization, which I think is really important.

**Comment by swtrse** [comment]
That works thx you are a lifesaver.

I can not speak for typescript/javascript but what I would do in C# create a class that has all the properties used in the hbs files (items, parameters, functions, ...). I would use this class with an injection framework in my project and made it the default class in the configuration if nothing eles is configured. I would then allow users to override the class and allow users to inject the customized class instead of the original one with the config.

I suspect with typescript this could be even done in an typesafe way. The logic of finding event, functions,... would be in that class an there would be an easy way to customize some or all functionality in an easy way. There is even the possibility to  provide variants of the class with preset use cases like only get events, functions from the actual file or from all files in the inheritance path.

**Comment by swtrse** [comment]
@frangio One last thing since I prefer typescript over javascript I played a bit to create a minimal typescript version for the helper.
I could not find any location where eq would be called so I skipt the implementation the helpers.ts I came up with looks like
````typescript
import { ContractDefinition, EventDefinition } from "solidity-ast";
import { Node } from "solidity-ast/node";
import { ASTDereferencer, findAll } from "solidity-ast/utils";
import { DocItemWithContext, DOC_ITEM_CONTEXT } from "solidity-docgen/dist/site";


export function allEvents(this: DocItemWithContext)
{
	if (this.nodeType ===  "ContractDefinition")
	{
		const deref: ASTDereferencer = this[DOC_ITEM_CONTEXT].build.deref;
		const parents: ContractDefinition[] = this.linearizedBaseContracts.map(deref("ContractDefinition"));
		
		const r: EventDefinition[] = parents.flatMap((p: Node) => [...findAll("EventDefinition", p)]);
		// console.log(`Events: ${this.canonicalName} -> ${r.map(e => e.name)}`);
		return r;
	}
}
```
In project using ts-node there is no need to call tsc and even debugging the helper works fine :)

**Comment by frangio** [comment]
`eq` is called in `{{#unless (eq nodeType "EventDefinition")}}` in the template I shared above!

That's great that you were able to set it up TypeScript though!
