### ISSUE TITLE
docgen usage

### ISSUE THREAD

**Issue by PedroReyes** [OpenZeppelin/solidity-docgen#390]
Hello,

📗 Versions
I have installed hardhat: `npm install --save-dev hardhat`

I have installed solidity doc-gen: `"solidity-docgen": "v0.6.0-beta.16"`

```
"dependencies": {
    "solidity-docgen": "v0.6.0-beta.16"
  },
  "devDependencies": {
    "hardhat": "2.9.9",
  }
```

🔨 Setup
My `hardhat.config.js` file contains the next:
```
import "solidity-docgen";

/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
  solidity: "0.7.3",
  docgen: {},
};
```

❌Problem
When executing `npx hardhat docgen`, the execution is the one for creating a project instead of creating any documentation:

```
$ npx hardhat docgen
888    888                      888 888               888
888    888                      888 888               888
888    888                      888 888               888
8888888888  8888b.  888d888 .d88888 88888b.   8888b.  888888
888    888     "88b 888P"  d88" 888 888 "88b     "88b 888
888    888 .d888888 888    888  888 888  888 .d888888 888
888    888 888  888 888    Y88b 888 888  888 888  888 Y88b.
888    888 "Y888888 888     "Y88888 888  888 "Y888888  "Y888

Welcome to Hardhat v2.9.9

? What do you want to do? ... 
> Create a basic sample project
  Create an advanced sample project
  Create an advanced sample project that uses TypeScript
  Create an empty hardhat.config.js
  Quit
```

I have followed the README that can be found in the version specified above: https://github.com/OpenZeppelin/solidity-docgen/tree/v0.6.0-beta.16. 

I have moved to v0.6.0 following the recommendation stated here by @frangio : https://github.com/OpenZeppelin/solidity-docgen/issues/389#issuecomment-1155638078. Should I downgrade to another beta in v0.6.0, @frangio ?

Thanks in advanced for the help.

Best regards,
Pedro Reyes.
CC: @spalladino

**Comment by frangio** [comment]
Can you try replacing `import "solidity-docgen";` with `require('solidity-docgen');` ?

**Comment by frangio** [comment]
The behavior you describe is very strange. I was not able to reproduce it. If my suggestion above doesn't change anything please upload a minimal reproduction.

**Comment by PedroReyes** [comment]
Hello @frangio ,

By replacing `import "solidity-docgen";` with `require('solidity-docgen');` I obtain the next result:

```
$ npx hardhat docgen
Downloading compiler 0.8.10
Compiled 23 Solidity files successfully
```
However, where is the documentation generated?

The changes I got are artifacts and ABI json files:

![image](https://user-images.githubusercontent.com/4096108/173977879-1cacfa9f-d2c2-401f-a0b1-cca0bc4aa59a.png)

Best regards,
Pedro Reyes.

**Comment by frangio** [comment]
Should be generated into `docs`.

**Comment by PedroReyes** [comment]
Hello @frangio ,

You are right, a `index.md` file is generated within the `docs` folder. 

❌ Problem

However, the content of this `index.md` file is the next one:

```
# Solidity API


```

I have a `Vault.sol`. The content of it is something like this:

```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.10;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/access/AccessControlEnumerable.sol";
import "@openzeppelin/contracts/security/Pausable.sol";

/// @title A vault for storing ether and tokens
/// @author Pedro Reyes
/// @notice This contract is for those weak hands that cannot hold!!
contract Vault is AccessControlEnumerable, Pausable {
    // 👨‍👩‍👦 Role-Based Access control
    bytes32 public constant ADMIN_ROLE = keccak256("ADMIN_ROLE");
    bytes32 public constant SWEEPER_ROLE = keccak256("SWEEPER_ROLE");

    // 💸 Owner => Token => Deposit
    mapping(address => VaultDeposit[]) public vaultDeposits;

    struct VaultDeposit {
        uint256 amount;
        uint256 lockEndTime;
        address token;
    }

    // 💰 Income
    uint256 public feePercentage;
    mapping(address => uint256) public feesCollectedPerToken;

    // 🔨
    constructor() {
        // . . . code here
    }

    /// @dev User can make individual deposits that will be locked for a certain time
    /// @param _token - ERC20 token address. address(0) if sending ether
    /// @param _amount - bigger than zero if sending ERC20 tokens
    /// @param _lockedTime - bigger than zero if sending ERC20 tokens. Example, 1 minute, 1 hour, 1 day
    function deposit(
        address _token,
        uint256 _amount,
        uint256 _lockedTime
    ) external payable whenNotPaused {
        // . . . code here
    }

    /// @dev Get fee for an amount of tokens
    /// @param _amount - bigger than zero if sending ERC20 tokens
    function getFee(uint256 _amount) public view returns (uint256) {
        // . . . code here
    }
}
```

✅ Expected result
I guess the result for that `index.md` file should be a compound of all my comments following the NatSpec documentation standard.

Thanks in advanced for your help, @frangio .

Best regards,
Pedro Reyes.

**Comment by frangio** [comment]
Is `Vault.sol` inside the `contracts` directory? Please make sure you have a basic understanding of how Hardhat is used before attempting to use this plugin.

**Comment by PedroReyes** [comment]
Hello @frangio ,

Yes, the `Vault.sol` contract is indeed within the `contracts` directory.

![image](https://user-images.githubusercontent.com/4096108/174454918-229b6d9e-531f-42e9-9fab-3495505cf4d4.png)

**Comment by frangio** [comment]
I will need you to provide a way for me to reproduce the problem.

**Comment by PedroReyes** [comment]
Hello @frangio ,

I have created this public repository so you can check yourself: https://github.com/PedroReyes/ethernaut/tree/docgen

Best regards,
Pedro Reyes

**Comment by frangio** [comment]
I run `hardhat docgen` in your repository and the documentation gets generated there as expected.

I did notice that `docs/index.md` includes the docs for dependencies so I published a new version that fixes this.

**Comment by PedroReyes** [comment]
Hello @frangio ,

Can you send me what generates for you? What I get is an empty file containing just the next info

```
# Solidity API


```

best regards,
Pedro Reyes.
