### ISSUE TITLE
docgen usage - empty doc file

### ISSUE THREAD

**Issue by PedroReyes** [OpenZeppelin/solidity-docgen#391]
Hello @frangio ,

I am following this issue you closed here: https://github.com/OpenZeppelin/solidity-docgen/issues/390. The problem persists with an empty `index.md` file

```
# Solidity API


```

👉 Video showing how I get an empty `index.md` documentation file

https://user-images.githubusercontent.com/4096108/174690882-1f4471bc-a591-46ac-a2b5-21537cd26700.mp4

Could you help me? You said you got it working on your environment directly cloning from my repository, no?

👉 Repository: https://github.com/PedroReyes/ethernaut/tree/docgen

best regards,
Pedro Reyes.

**Comment by frangio** [comment]
Can you please sharethe contents of `artifacts/build-info`? I think this is related to Windows.

**Comment by PedroReyes** [comment]
Hello @frangio ,

Any news?

Best regards,
Pedro Reyes.

**Comment by frangio** [comment]
Please try the latest version. I made some changes that may fix this, which is an issue with Windows.

**Comment by PedroReyes** [comment]
Hello @frangio ,

We keep having progress but not yet solved unfortunately. Here it is the output:

```
$ npx hardhat docgen
Compiled 15 Solidity files successfully
An unexpected error occurred:

Error: Cannot find module 'C:\blockchain\ethernaut\node_modules\solidity-docgen\src\themes\markdown\helpers'
Require stack:
- C:\blockchain\ethernaut\node_modules\solidity-docgen\dist\templates.js
- C:\blockchain\ethernaut\node_modules\solidity-docgen\dist\main.js
- C:\blockchain\ethernaut\node_modules\solidity-docgen\dist\index.js
- C:\blockchain\ethernaut\hardhat.config.js
- C:\blockchain\ethernaut\node_modules\hardhat\internal\core\config\config-loading.js
- C:\blockchain\ethernaut\node_modules\hardhat\internal\cli\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at C:\blockchain\ethernaut\node_modules\solidity-docgen\src\templates.ts:85:13
    at readHelpers (C:\blockchain\ethernaut\node_modules\solidity-docgen\src\templates.ts:85:13)
    at readTemplates (C:\blockchain\ethernaut\node_modules\solidity-docgen\src\templates.ts:69:14)
    at readThemes (C:\blockchain\ethernaut\node_modules\solidity-docgen\src\templates.ts:110:21)
    at loadTemplates (C:\blockchain\ethernaut\node_modules\solidity-docgen\src\templates.ts:23:18)
    at main (C:\blockchain\ethernaut\node_modules\solidity-docgen\src\main.ts:19:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\blockchain\\ethernaut\\node_modules\\solidity-docgen\\dist\\templates.js',
    'C:\\blockchain\\ethernaut\\node_modules\\solidity-docgen\\dist\\main.js',
    'C:\\blockchain\\ethernaut\\node_modules\\solidity-docgen\\dist\\index.js',
    'C:\\blockchain\\ethernaut\\hardhat.config.js',
    'C:\\blockchain\\ethernaut\\node_modules\\hardhat\\internal\\core\\config\\config-loading.js',
    'C:\\blockchain\\ethernaut\\node_modules\\hardhat\\internal\\cli\\cli.js'
  ]
}
```

Path problem - zoom in `C:\blockchain\ethernaut\node_modules\solidity-docgen\src\themes\markdown\helpers`

![image](https://user-images.githubusercontent.com/4096108/177552388-9ea69ae3-d2e1-4dd8-a024-d269a2626646.png)

Let me know if you need anything from my side. I am available for zoom too. 

Best regards,
Pedro Reyes.

**Comment by PedroReyes** [comment]
Hello @frangio ,

Current output with tag `"solidity-docgen": "v0.6.0-beta.19"`: 

```
$ npx hardhat docgen
Compiled 15 Solidity files successfully
An unexpected error occurred:

[Error: ENOENT: no such file or directory, mkdir 'C:\blockchain\ethernaut\C:\blockchain\ethernaut\docs'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'C:\\blockchain\\ethernaut\\C:\\blockchain\\ethernaut\\docs'   
}
```

Best regards,
Pedro Reyes

**Comment by frangio** [comment]
Ok, identified that issue. Please give it another try. Sorry about the back and forth.

**Comment by PedroReyes** [comment]
Hello @frangio ,

Don't worry about the back and forth ✌ it is part of the game!

Problem solved. Thanks for your support, @frangio ! 🎉🎉🎉 Have a nice weekend!

Best regards,
Pedro Reyes.

![image](https://user-images.githubusercontent.com/4096108/178118110-c93d1a9c-a780-4249-92c1-1b098f348183.png)
