### ISSUE TITLE
Add a way to exclude / ignore folders from being documented

### ISSUE THREAD

**Issue by wei3erHase** [OpenZeppelin/solidity-docgen#394]
A hardhat repo can have many contracts that need to be compiled, but not documented, for instance `ForTest` contracts, where having a documentation would seem unnecessary:
A repo can have the following structure
- solidity
    - contracts
        - for-test
    - interfaces

The issue is to provide a way of ignoring the `for-test` folder, so that documentation is only generated from `contracts` and `interfaces`

**Comment by Pedroa0710** [comment]
I never did this before I don't know how,pleass help me with this

**Comment by frangio** [comment]
Added `exclude` to the configuration options.

https://github.com/OpenZeppelin/solidity-docgen/blob/c8ab3716589fe650b33755414951cd68e47a73f0/src/config.ts#L37-L40

```
docgen: {
  exclude: ['for-test'],
}
```

**Comment by frangio** [comment]
The directory structure you shared looks odd. Why is `interfaces` outside of `contracts`?

**Comment by wei3erHase** [comment]
found that is a good practise to keep paths similar on `for-test` contracts
