### ISSUE TITLE
docgen as a library with hardhat

### ISSUE THREAD

**Issue by PedroReyes** [OpenZeppelin/solidity-docgen#398]
Hello @frangio ,

👁 Context
I am trying to use docgen as a library in order to update automatically the docs as part of a husky process that runs before a git commit

💻 System setup
* OS: `Windows 10`
* node: `v18.2.0`
* npm `8.9.0`
* solidity-docgen: `0.6.0-beta.20`

🔁 Reproduction
Repository: https://github.com/PedroReyes/ethernaut/blob/docgen/husky/docgen.mjs

I have commented the code that is giving me the issue. Uncomment it and run `node husky/docgen.mjs`

❌ Problem
Is the next code the right way to use docgen as a library? When I run:

```
const json = JSON.parse(
  fs.readFileSync("artifacts/contracts/Vault.sol/Vault.json")
);

await docgen([{ output: json }]);
```

What I obtain is:

```
$ node husky/docgen.mjs 
� This is a beta version of docgen.js. It is not yet production ready.        
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at clone (C:\blockchain\ethernaut\node_modules\solidity-docgen\dist\utils\clone.js:9:29)
    at buildSite (C:\blockchain\ethernaut\node_modules\solidity-docgen\dist\site.js:27:41)
    at main (C:\blockchain\ethernaut\node_modules\solidity-docgen\dist\main.js:20:39)
    at file:///C:/blockchain/ethernaut/husky/docgen.mjs:74:9
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)       
    at async loadESM (node:internal/process/esm_loader:85:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

In the documentation states that `ast` is necessary but in the `Vault.json` generated by hardhat that key is not part of the json structure.

I assumed that docgen worked with hardhat by default so there must be something wrong I am doing. Could you help me out?

Thanks in advance.

Best regards,
Pedro Reyes.

**Comment by frangio** [comment]
If this is a Hardhat project my recommendation is to use it through Hardhat as `hre.run('docgen')` (`import hre from 'hardhat'`). Does this work for you?

**Comment by PedroReyes** [comment]
Hello @frangio ,

No, it does not work. The output is the next one:

```
$ node husky/docgen.mjs
� This is a beta version of docgen.js. It is not yet production ready.
(node:19652) UnhandledPromiseRejectionWarning: HardhatError: HH303: Unrecognized task docgen
    at Environment.run (C:\blockchain\ethernaut\node_modules\hardhat\internal\core\runtime-environment.js:47:23)
    at file:///C:/blockchain/ethernaut/husky/docgen.mjs:76:7
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have an empty `docgen:{}` json key in the last commit here: https://github.com/PedroReyes/ethernaut/commits/docgen. Shall I add something to the `hardhat.config.json` here:

```
require("@nomiclabs/hardhat-waffle");
require("solidity-docgen");

// You need to export an object to set up your config
// Go to https://hardhat.org/config/ to learn more

/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
  solidity: "0.8.4",
  docgen: {},
};
```

Best regards,
Pedro Reyes.

**Comment by frangio** [comment]
Ok I can see what the error is. In the meantime, please use `require("solidity-docgen/hardhat")` instead of `require("solidity-docgen")` in your config file.

**Comment by frangio** [comment]
Sorry I just realized why this is happening. You're importing `solidity-docgen` before you import `hardhat`. Change it like this:

```diff
-import { docgen } from "solidity-docgen";
 import hre from "hardhat";
```

**Comment by frangio** [comment]
I released a fix so this works even without the suggestion I made above. https://github.com/OpenZeppelin/solidity-docgen/commit/9f99e6a8ea67053182512e9edabc500adb8db893
