### ISSUE TITLE
docgen - working with templates - solidity-docgen: 0.6.0-beta.22

### ISSUE THREAD

**Issue by PedroReyes** [OpenZeppelin/solidity-docgen#402]
Hello,

👁 Context
I am trying to see the possibility of creating my own template. For that I have taken this from another issue in the backlog: https://github.com/PedroReyes/ethernaut/tree/docgen/contracts/templates.

I have also applied the last version `solidity-docgen: 0.6.0-beta.22` that fixed the last issue I opened here: https://github.com/OpenZeppelin/solidity-docgen/issues/399

💻 System setup

OS: Windows 10
node: v14.18.1
npm 6.14.15
solidity-docgen: 0.6.0-beta.22

🔁 Reproduction
Repository: https://github.com/PedroReyes/ethernaut/blob/docgen/husky/docgen.mjs

❌ Problem

I have added the directory to the `hardhat.config.js` file:
```
module.exports = {
  solidity: "0.8.4",
  docgen: {
    templates: "./contracts/templates",
    pages: "files"
  }
};
```
However, I am getting the next output in the markdown generated files when running `npx hardhat docgen` using a template folder:

```
# Solidity API






```

If I remove the template folder from the `hardhat.config.js file` then everything is generated automatically with the default template.

Thanks in advanced for your help @frangio .

Best regards,
Pedro Reyes.

**Comment by frangio** [comment]
The tempalte you used is designed for solidity-docgen 0.5. See [this directory](https://github.com/OpenZeppelin/solidity-docgen/tree/master/src/themes/markdown) for current template examples.
