### ISSUE TITLE
docgen - working with templates - solidity-docgen: 0.6.0-beta.22

### ISSUE THREAD

**Issue by PedroReyes** [OpenZeppelin/solidity-docgen#403]
Hello,

## 👁 Context
I am trying to see the possibility of creating my own template. 

I have applied the last version `solidity-docgen: 0.6.0-beta.22` that fixed the last issue I opened here: https://github.com/OpenZeppelin/solidity-docgen/issues/402

I checked [this directory looking for examples](https://github.com/OpenZeppelin/solidity-docgen/tree/master/src/themes/markdown)

## 💻 System setup

* OS: Windows 10
* node: v18.2.0
* npm 8.9.0
* solidity-docgen: 0.6.0-beta.22

## 🔁 Reproduction
Repository: https://github.com/PedroReyes/ethernaut/tree/docgen

## ❌ Problem

The very first problem I want to solve is rather simple. I have the next `contract.hbs` with the next content:

```
{{h}} {{name}}.sol 

Just testing
```

However, I am getting the next output in the markdown generated files when running `npx hardhat docgen`:

```
# Solidity API

## Greeter.sol 

Just testing
```

### 👉 Problem 1 - `# Solidity AP`
It seems that no matter what I put in there, `# Solidity API` is placed at the top instead of my fixed string. 

I want the name of the contract to appear at the top so when I use a markdown site generator, the name of the content is obtained from the very first line of my markdown.

### 👉 Problem 2 - `H index`
How do I control the index of the title so instead of `## Greeter.sol`  I have `# Greeter.sol `

Thanks in advanced for your help @frangio .

Best regards,
Pedro Reyes.

**Comment by frangio** [comment]
You should override the [`page.hbs`](https://github.com/OpenZeppelin/solidity-docgen/blob/master/src/themes/markdown/page.hbs) template.
