### ISSUE TITLE
Not generating good content for params and returns 

### ISSUE THREAD

**Issue by Nazeim** [OpenZeppelin/solidity-docgen#408]
@frangio

I used the tool to generate md files from sol files but I'd say it's mostly missing a description of what's what: which ones are parameters (@param), which is the return value (@return) and which are just extra observations for developers (in this case, @dev). In particular I found it hard to distinguish the tables there (looking at the code, the 1st one is the input parameter, while the 2nd is the return value).

Do you know how to display a better content?

![screen_shot_2022-08-30_at_6 20 15_pm](https://user-images.githubusercontent.com/15310211/188143980-b7e79d6f-114f-44ba-b1e8-33d2e982a1f0.png)

**Comment by frangio** [comment]
This is generated using this template: https://github.com/OpenZeppelin/solidity-docgen/blob/a7b9b8c280bcce3e4409c8f1a6d3172e33815bdb/src/themes/markdown/common.hbs

You can customize the output by adding to your Hardhat config:
```
docgen: { templates: 'docs-templates' }
```

Then copying the `common.hbs` file into a directory `docs-templates` on your project, and customizing it how you want.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/solidity-docgen/commit/6460a1e8e0e3546ac7c5e8fe3ef493544f8e22fe and published in the latest release.
