### ISSUE TITLE
`npx solidity-docgen` fails with mysterious error if too many lines of code (including comments) in /contracts contents

### ISSUE THREAD

**Issue by kyzooghost** [OpenZeppelin/solidity-docgen#409]
**Bug:** Attempted to run`npx solidity-docgen --solc-module solc-0.8` on /contract directory containing 179 .sol files, got the following error:

```bash
Bus error: 10
```

A colleague got the following error on their local:

```bash
RuntimeError: memory access out of bounds
TypeError: Cannot convert undefined or null to object
Error: Solidity was unable to compile. Unknown exception during compilation: std::bad_alloc
```

**Details:**
Was frustrated by this mysterious bug with no stack trace to look into. Initially thought there was a line of code in .sol files causing this error. However I found that even a .sol file almost completely commented out would cause this error, and after a certain number of lines of code, any additional lines of code (even comments) would cause this error.

Attempted `npx solidity-docgen --solc-module solc-0.8` on same /contracts files but split into two partitions, was able to successfully use docgen command without the error.

**Comment by frangio** [comment]
Is there a change you can share the code?

What version of `solidity-docgen` are you using?

**Comment by kyzooghost** [comment]
This for version ^0.5.16 from the root directory of the following repo: https://github.com/solace-fi/solace-core/tree/feat/Bribes

**Comment by frangio** [comment]
Version 0.5 is not actively supported anymore. Let me know if 0.6 is not viable for this project and I can help fix that.
