### ISSUE TITLE
Empty lines are undesirably removed

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/solidity-docgen#41]
Example input file: [BancorConverter.sol](https://github.com/bancorprotocol/contracts/blob/master/solidity/contracts/converter/BancorConverter.sol).

Example output file: [BancorConverter.md](https://github.com/bancorprotocol/contracts/blob/master/solidity/docgen/docs/converter/BancorConverter.md).

As you can see, at the top of the input file, under the first `@dev` tag (i.e., at the contract-level documentation), consecutive lines are explicitly and deliberately separated by an empty line, in order to ensure that those lines will not appear as a single line when the output file is rendered in an MD viewer.

However, all the empty lines are removed by `solidity-docgen`.

It might be more visible if you view the output file in Edit format, by clicking the Pencil button at the top-right corner (or simply [here](https://github.com/bancorprotocol/contracts/edit/master/solidity/docgen/docs/converter/BancorConverter.md)).

Thanks

**Comment by frangio** [comment]
solc's handling of newlines in natspec comments is broken. I've had to patch a few things to get the output that the user intended, but in this specific case there's nothing we can do because solc collapse newlines and we don't know how many there were originally.

Adding leading asterisks does result in keeping the multiple newlines and is what you should do in the linked file:

```
/**
 * @dev Bancor Converter
 *
 * The Bancor converter allows for conversions between a Smart Token and other ERC20 tokens and between different ERC20 tokens and themselves. 
 *
 * The ERC20 connector balance can be virtual, meaning that the calculations are based on the virtual balance instead of relying on the actual connector balance.
```

**Comment by barakman** [comment]
@frangio:
Thank you.
Your description about solc's handling of newlines in natspec comments being broken, is sufficiently convincing (as a reason for why `solidity-docgen` cannot resolve this specific problem).

More importantly, your suggestion for filling a column of asterisks does resolve the problem!
BTW, it also resolves the problem of bullets indentation, which I believe I have mentioned in a separate GitHub issue.

One point to note, is that there shouldn't be more than one space character after each asterisk, otherwise the entire line is omitted from the output of `solidity-docgen` altogether.

Thanks :)
