### ISSUE TITLE
Exclude directories does not actually exclude docs from being generated

### ISSUE THREAD

**Issue by d1onys1us** [OpenZeppelin/solidity-docgen#419]
## Description of problem
Here is the configuration within `hardhat.config.ts`:
```
const config = {
...
  docgen: {
    exclude: ["./test"],
    pages: "files",
    templates: "./solidity-docgen/templates",
  },
...
};
  ```
  
I have a folder `test`, in my contracts src directory. I have tried many patterns such as `test`, `./test/`, `**/test/**`,`test/**/*`, etc. None of them seem to work. My `templates` directory is just a copy of the `templates/markdown` directory in this repo, because I wasn't sure how else to override the default templates.

Additionally, on the topic of things getting generated -- I have noticed two more random doc generations:
 - `elin` folder is generated with OpenZeppelin contracts in it, however I do not have these contracts in my source directory.
 - `console.md` file is generated in the root.
 
 ## Desired resolution
- Correctly exclude files specified in exclude
- Exclude the extraneous files I have noticed above: `elin/*` and `console.md`

**Comment by frangio** [comment]
I can't reproduce this. `exclude: ['./test']` should work. Are you deleting the directory and it gets regenerated? If so, please share your repo so I can try it out.

`elin` might be something you had previously... you should try `hardhat clean` and then generate docs again.

`console.md` is odd, it may also be the above. Are you using the latest 0.6 version?

**Comment by d1onys1us** [comment]
i will close this issue because it turns out the elin and console.md files being generated were because i also had another docgen tool installed, and both of them were running on compile.
