### ISSUE TITLE
Support for Foundry

### ISSUE THREAD

**Issue by paulrberg** [OpenZeppelin/solidity-docgen#427]
It is currently not possible to use solidity-docgen in a Foundry-based project - or at least, it is not possible to change the default settings.

**Comment by frangio** [comment]
It should be possible to wire it up for use with Foundry by passing in the solc output as described [here in the readme](https://github.com/OpenZeppelin/solidity-docgen#as-a-library).

What would you expect usage with Foundry to look like? I'm not familiar with extending Foundry so I don't know if it would be some sort of plugin or a Solidity library or what.

**Comment by paulrberg** [comment]
I think what I was getting at is to turn this into a CLI, so that solidity-docgen can be run from the command-line and users don't have to import it in a Node.js environment anymore.

In Foundry, there is the [ffi](https://book.getfoundry.sh/cheatcodes/ffi?highlight=ffi#ffi) cheatcode, which lets users run arbitrary shell commands from within Solidity.

**Comment by samlaf** [comment]
I managed to get solidity-docgen to work with Foundry by using https://book.getfoundry.sh/config/hardhat

**Comment by paulrberg** [comment]
I just found out that Foundry offers a similar functionality to `solidity-docgen` natively.

There is `forge cmd`, which parses NatSpec comments to autogenerate documentation.

I will close this issue.
