### ISSUE TITLE
command not found: solidity-docgen

### ISSUE THREAD

**Issue by maxdesalle** [OpenZeppelin/solidity-docgen#429]
After executing the `npm install solidity-docgen` command, the `npx solidity-docgen` returns `command not found: solidity-docgen`.

Interestingly, the `solidity-docgen` executable is nowhere to be found in the `node_modules/.bin/` folder after executing the `npm install solidity-docgen` command.

Unfortunately, related issues like #8 and #105 don't seem to offer a fix for this particular problem.

**Comment by frangio** [comment]
The new version of solidity-docgen isn't used like this. It's mainly a Hardhat plugin, you have to set it up in your Hardhat config and run with `hardhat docgen`.
