### ISSUE TITLE
anchor is always empty

### ISSUE THREAD

**Issue by migoldfinger** [OpenZeppelin/solidity-docgen#441]
Hello,

I tired to use {{anchor}} in one of my templates but it did turn out that it is always empty.
I looked into the code and see that anchor is generated with slug so i suspect that slug is empty too.
I did not find any documentation of how to set the slug so I assumed it is set automatically.

So either anchor and slug do not work at the moment and need fixing or there is a need for an working example of how to use anchor in solidity-docgen.

**Comment by frangio** [comment]
What version are you running?

**Comment by migoldfinger** [comment]
I just added it yesterday to my package.json
solidity-docgen": "^0.6.0-beta.35"

**Comment by frangio** [comment]
Actually there is no `anchor` by default in 0.6. For OpenZeppelin Contracts we define that here:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/1642b6639b93e3b97be163d49827e1f56b81ca11/docs/templates/properties.js#L4

**Comment by migoldfinger** [comment]
thx thats helping a lot.
