### ISSUE TITLE
Ignore/exclude specific files or contracts inside files

### ISSUE THREAD

**Issue by vladikopl01** [OpenZeppelin/solidity-docgen#444]
Hello!

Is there a possibility to ignore specific contract files by providing a path to them to `exclude` property in `docgen` config?

If not, it would be a great feature to have to use contract paths as other plugins for hardhat, as follows:

- For a specific file: `contracts/tokens/Tokens.sol`
- Or even for a specific contract inside one file: `contracts/tokens/Tokens.sol:ERC20`

Also, could someone help me out with excluding contract files in such a way? Or maybe specify somehow a contract file which only should be documented? All contract files are located at `contracts/` and it's forbidden to move files in different folders. 

Would appreciate any help.

**Comment by frangio** [comment]
I believe you should be able to have this file exluded by adding to your Hardhat config:

```
docgen: {
  exclude: ['tokens/Tokens.sol'],
},
```

**Comment by vladikopl01** [comment]
Damn, sorry, definitely a stupid issue from my side.
@frangio Thanks, it works
