### ISSUE TITLE
Not able to access the file outside of allowed directories

### ISSUE THREAD

**Issue by satyamakgec** [OpenZeppelin/solidity-docgen#5]
I am using the command as in the README but getting the following error - 

> /Users/satyamagrawal/Repositories/polymath-core_v2/contracts/modules/TransferManager/GeneralTransferManager.sol:4:1: Error: Source "openzeppelin-solidity/contracts/math/SafeMath.sol" not found: File outside of allowed directories.
import "openzeppelin-solidity/contracts/math/SafeMath.sol";
^---------------------------------------------------------^
/Users/satyamagrawal/Repositories/polymath-core_v2/contracts/modules/TransferManager/ManualApprovalTransferManager.sol:4:1: Error: Source "openzeppelin-solidity/contracts/math/SafeMath.sol" not found: File outside of allowed directories.
import "openzeppelin-solidity/contracts/math/SafeMath.sol";
^-------------------------------------------------------------^
/Users/satyamagrawal/Repositories/polymath-core_v2/contracts/tokens/SecurityToken.sol:3:1: Error: Source "openzeppelin-solidity/contracts/token/ERC20/ERC20.sol" not found: File outside of allowed directories.
import "openzeppelin-solidity/contracts/token/ERC20/ERC20.sol";
^-------------------------------------------------------------^

Cmd used - 
`SOLC_ARGS=‘openzeppelin-solidity=~/Repositories/polymath-core_v2/node_modules/openzeppelin-solidity’  \
npx solidity-docgen ~/Repositories/polymath-core_v2 ~/Repositories/polymath-core_v2/contracts ~/Repositories/polymath-core_v2/docs-examples-from-docusaurus `

**Comment by ealmansi** [comment]
Hi Satyam.

Could you please verify that you are using `solc` version v0.4.21 or newer?
Also, try out writing out the full path instead of the shortened version with `~`.
That is, writing `/Users/satyamagrawal/Repositories/polymath-core_v2` instead of `~/Repositories/polymath-core_v2`, and the same for all other paths in the command.

**Comment by mariano-aguero** [comment]
Hi @satyamakgec , remove the npx form the command(its not necessary) and add full path, must be like this

```
SOLC_ARGS='openzeppelin-solidity=/YOUR-PATH-TO-THE-PROYECT/node_modules/openzeppelin-solidity' \
solidity-docgen /YOUR-PATH-TO-THE-PROYECT /YOUR-PATH-TO-THE-PROYECT/contracts /YOUR-PATH-TO-THE-PROYECT/docs
```

**Comment by satyamakgec** [comment]
Thanks @mariano-aguero It works.
