### ISSUE TITLE
Version 0.3.9 omits the constructor when natspec is not provided

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/solidity-docgen#76]
Here is the relevant part in my template (HBS) file:
```
{{#ownFunctions}}
{{#if (or (eq visibility "public") (eq visibility "external"))}}
# Function `{{name}}({{args}}){{#if outputs}} → {{outputs}}{{/if}}` {#{{anchor~}} }
{{#if natspec.devdoc}}{{natspec.devdoc}}{{else}}No description{{/if}}
{{#if natspec.params}}
## Parameters:
{{#natspec.params}}
- `{{param}}`: {{description}}
{{/natspec.params}}
{{/if}}
{{#if natspec.returns}}
## Return Values:
{{#natspec.returns}}
- {{param}} {{description}}
{{/natspec.returns}}
{{/if}}
{{/if}}
{{/ownFunctions}}
```
Prior to v0.3.9, every function which is not preceded by natspec, appears in the output.
In v0.3.9, every constructor which is not preceded by natspec, is omitted from the output.

I find this inconsistent.
IMO, either keep **all** functions with no natspec, or remove **all** functions with no natspec.
Preferably keep them, because I'd still want my users to know about those functions (and even have them asking me for documentation should they need it).

Here is an output example prior v0.3.9:
```
# Functions:

- [`constructor()`](#BancorFormula-constructor--)

- [`calculatePurchaseReturn(uint256 _supply, uint256 _reserveBalance, uint32 _reserveRatio, uint256 _depositAmount)`](#BancorFormula-calculatePurchaseReturn-uint256-uint256-uint32-uint256-)

- [`calculateSaleReturn(uint256 _supply, uint256 _reserveBalance, uint32 _reserveRatio, uint256 _sellAmount)`](#BancorFormula-calculateSaleReturn-uint256-uint256-uint32-uint256-)

- [`calculateCrossReserveReturn(uint256 _fromReserveBalance, uint32 _fromReserveRatio, uint256 _toReserveBalance, uint32 _toReserveRatio, uint256 _amount)`](#BancorFormula-calculateCrossReserveReturn-uint256-uint32-uint256-uint32-uint256-)

- [`calculateCrossConnectorReturn(uint256 _fromConnectorBalance, uint32 _fromConnectorWeight, uint256 _toConnectorBalance, uint32 _toConnectorWeight, uint256 _amount)`](#BancorFormula-calculateCrossConnectorReturn-uint256-uint32-uint256-uint32-uint256-)

# Function `constructor()` {#BancorFormula-constructor--}

No description

# Function `calculatePurchaseReturn(uint256 _supply, uint256 _reserveBalance, uint32 _reserveRatio, uint256 _depositAmount) → uint256` {#BancorFormula-calculatePurchaseReturn-uint256-uint256-uint32-uint256-}

...
```
And here is the corresponding output example on v0.3.9:
```
# Functions:

- [`calculatePurchaseReturn(uint256 _supply, uint256 _reserveBalance, uint32 _reserveRatio, uint256 _depositAmount)`](#BancorFormula-calculatePurchaseReturn-uint256-uint256-uint32-uint256-)

- [`calculateSaleReturn(uint256 _supply, uint256 _reserveBalance, uint32 _reserveRatio, uint256 _sellAmount)`](#BancorFormula-calculateSaleReturn-uint256-uint256-uint32-uint256-)

- [`calculateCrossReserveReturn(uint256 _fromReserveBalance, uint32 _fromReserveRatio, uint256 _toReserveBalance, uint32 _toReserveRatio, uint256 _amount)`](#BancorFormula-calculateCrossReserveReturn-uint256-uint32-uint256-uint32-uint256-)

- [`calculateCrossConnectorReturn(uint256 _fromConnectorBalance, uint32 _fromConnectorWeight, uint256 _toConnectorBalance, uint32 _toConnectorWeight, uint256 _amount)`](#BancorFormula-calculateCrossConnectorReturn-uint256-uint32-uint256-uint32-uint256-)

# Function `calculatePurchaseReturn(uint256 _supply, uint256 _reserveBalance, uint32 _reserveRatio, uint256 _depositAmount) → uint256` {#BancorFormula-calculatePurchaseReturn-uint256-uint256-uint32-uint256-}

...
```
Thanks

**Comment by frangio** [comment]
Yes, this change was by design. The thing is, all Solidity contracts implicitly have a constructor without arguments. `solidity-docgen` used to include a constructor in its output if it was explicit in the source file, but I think this behavior was misleading. There isn't necessarily anything special about an explicit constructor. It _may_ have special behavior, but from the point of view of the contract _interface_ there is no difference, and I believe the role of automatic documentation generation is to properly document the interface. If there is anything special about the behavior of this constructor, it should be documented in natspec, and then it will be included in the output.

Additionally, if the constructor interface is not the default one (i.e. it has arguments, or it is internal) we also do include it in the output.

**Comment by barakman** [comment]
Hmmm...
Actually it makes perfect sense - a constructor which takes no argument should be of no interest for the user (unless, for some reason, I've chosen to document it explicitly).
It is just like the default constructor added implicitly by the compiler (which is not added to the documentation, just like you said).
OK, thank you for clearing that out with a logical reasoning :)

**Comment by frangio** [comment]
Glad we agree on that!
