### ISSUE TITLE
solidity-docgen: command not found

### ISSUE THREAD

**Issue by maptuhec** [OpenZeppelin/solidity-docgen#8]
I am trying to execute and create a solidity documentation. As I read from the Readme and when I execute this command: 

`solidity-docgen /Users/martingrigorov/Work/Projects/LockChain/DApp /Users/martingrigorov/Work/Projects/LockChain/DApp/contracts /Users/martingrigorov/Work/Projects/LockChain/DApp/docs  `

It fails with the imports error. So I have modified and run the second command which should handle the imports: 
`SOLC_ARGS='openzeppelin-solidity=/Users/martingrigorov/Work/Projects/LockChain/DApp/contracts/node_modules/openzeppelin-solidity' \ solidity-docgen /Users/martingrigorov/Work/Projects/LockChain/DApp /Users/martingrigorov/Work/Projects/LockChain/DApp/contracts /Users/martingrigorov/Work/Projects/LockChain/DApp/docs  `

And how I have the following error: 

`-bash:  solidity-docgen: command not found`

I am using :

`solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Darwin.appleclang`

Also I am using MacBook if that helps in someway.

Any ideas to help?

**Comment by maxpiasevoli** [comment]
Remove the \ so that the command is 

SOLC_ARGS='openzeppelin-solidity=/Users/martingrigorov/Work/Projects/LockChain/DApp/contracts/node_modules/openzeppelin-solidity' solidity-docgen /Users/martingrigorov/Work/Projects/LockChain/DApp /Users/martingrigorov/Work/Projects/LockChain/DApp/contracts /Users/martingrigorov/Work/Projects/LockChain/DApp/docs

**Comment by maptuhec** [comment]
I tried to remove the \, and when I do again the imports fail. 

Any other thoughts ?

**Comment by maptuhec** [comment]
Hey Guys, any update on this issue?

**Comment by frangio** [comment]
@maptuhec Try setting the `SOLC_ARGS` variable before executing the command, running `export SOLC_ARGS=...`.

**Comment by maptuhec** [comment]
hey @frangio I have tried to set SOLC_ARGS and I managed to do it, but after the I run only the 
`solidity-docgen /Users/martingrigorov/Work/Projects/LockChain/DApp /Users/martingrigorov/Work/Projects/LockChain/DApp/contracts /Users/martingrigorov/Work/Projects/LockChain/DApp/docs`

and again the imports are failing

**Comment by frangio** [comment]
@maptuhec Please show me the full list of commands that you're running so I can offer better help.

**Comment by maptuhec** [comment]
@frangio I have tried with the following commands:
`SOLC_ARGS='openzeppelin-solidity=/Users/martingrigorov/Work/Projects/LockChain/DApp/contracts/node_modules/openzeppelin-solidity' \ solidity-docgen /Users/martingrigorov/Work/Projects/LockChain/DApp /Users/martingrigorov/Work/Projects/LockChain/DApp/contracts /Users/martingrigorov/Work/Projects/LockChain/DApp/docs`

With this commands the error that appears is the following:
`-bash: solidity-docgen: command not found`

I have tried your suggestion to set the `SOLC_ARGS ` as a variable with:

`SOLC_ARGS='openzeppelin-solidity=/Users/martingrigorov/Work/Projects/LockChain/DApp/contracts/node_modules/openzeppelin-solidity'`

and after `echo $SOLC_ARGS` i get the following:

`openzeppelin-solidity=/Users/martingrigorov/Work/Projects/LockChain/DApp/contracts/node_modules/openzeppelin-solidity`

which I believe is correct

After that I am running the solidity docgen command:

`solidity-docgen /Users/martingrigorov/Work/Projects/LockChain/DApp /Users/martingrigorov/Work/Projects/LockChain/DApp/contracts /Users/martingrigorov/Work/Projects/LockChain/DApp/docs`

And the imports are failing again.

This is the full set of commands and scenarios that I have tested and executed

**Comment by frangio** [comment]
>I have tried your suggestion to set the SOLC_ARGS as a variable with: ...

It's important that you `export` this variable so that running programs inherit the variable. Write `expor SOLC_ARGS=...`.

**Comment by maptuhec** [comment]
@frangio Sorry mistake in copying the commands I actually do 
`export SOLC_ARGS='openzeppelin-solidity=/Users/martingrigorov/Work/Projects/LockChain/DApp/contracts/node_modules/openzeppelin-solidity'`

and then the echo command shows the right path to the variable

`echo $SOLC_ARGS` shows :
`openzeppelin-solidity=/Users/martingrigorov/Work/Projects/LockChain/DApp/contracts/node_modules/openzeppelin-solidity`

**Comment by terjanyan** [comment]
I have the same problem

**Comment by frangio** [comment]
Closing the issue as it does not apply to the new v0.2 version (still in alpha, see #23 for details).
