### ISSUE TITLE
Multiple import statements from outside modules 

### ISSUE THREAD

**Issue by maxpiasevoli** [OpenZeppelin/solidity-docgen#9]
I understand that if there's an import statement from a node module like openzeppelin-solidity, then you have to use: 

SOLC_ARGS='openzeppelin-solidity=PATH_TO_OPENZEPPELIN_MOD' 

in order for solidity-docgen to find the files, but what if there are import statements from two modules, like openzeppelin-solidity and zos-lib in a single smart contract? Is there a way to pass multiple args to SOLC_ARGS? 

I tried: 

SOLC_ARGS = 'openzeppelin-solidity=*first path here*;zos-lib=*second path here*' 

but I received the error:  'Error: Command line operation failed with code 127. 
Standard error output: /bin/sh: 1: zos-lib=*path here*: not found'

**Comment by frangio** [comment]
Assuming this was resolved with @aleybovich's suggestion above. Thank you both!
